/**
 * @file Mock data for the dev preview page (`/_dev/dag-mocks`).
 *
 * Lives under __mocks__ to make it obvious this is **not** production data.
 * Shapes mirror the contract DTOs from `../types.js` (and `models/dags.py`).
 *
 * Keep this file the one place where mock payloads live so we have a single
 * spot to update when the contract evolves.
 */

/** @type {import('../types.js').TaskInstance[]} */
export const SAMPLE_TASK_INSTANCES = [
  {
    task_id: 'fetch_source',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'success',
    raw_state: 'success',
    try_number: 1,
    max_tries: 3,
    start_date: '2026-05-20T15:00:01Z',
    end_date: '2026-05-20T15:00:18Z',
    duration_ms: 17_000,
    operator: 'PythonOperator',
    pool: 'default_pool',
    queue: 'default',
    executor_config: {},
    note: null,
  },
  {
    task_id: 'profile_table',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'success',
    raw_state: 'success',
    try_number: 1,
    max_tries: 3,
    start_date: '2026-05-20T15:00:19Z',
    end_date: '2026-05-20T15:01:04Z',
    duration_ms: 45_000,
    operator: 'PythonOperator',
    pool: 'default_pool',
    queue: 'default',
    executor_config: {},
    note: null,
  },
  {
    task_id: 'train_model',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'running',
    raw_state: 'running',
    try_number: 2,
    max_tries: 3,
    start_date: '2026-05-20T15:03:11Z',
    end_date: null,
    duration_ms: null,
    operator: 'SparkSubmitOperator',
    pool: 'spark_pool',
    queue: 'spark',
    executor_config: {},
    note: 'Re-running after OOM on try 1.',
  },
  {
    task_id: 'validate_synthetic',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'queued',
    raw_state: 'scheduled',
    try_number: 1,
    max_tries: 3,
    start_date: null,
    end_date: null,
    duration_ms: null,
    operator: 'PythonOperator',
    pool: 'default_pool',
    queue: 'default',
    executor_config: {},
    note: null,
  },
  {
    task_id: 'export_to_s3',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'none',
    raw_state: 'none',
    try_number: 0,
    max_tries: 3,
    start_date: null,
    end_date: null,
    duration_ms: null,
    operator: 'S3CreateObjectOperator',
    pool: 'default_pool',
    queue: 'default',
    executor_config: {},
    note: null,
  },
  {
    task_id: 'notify_failed_branch',
    run_id: 'manual__2026-05-20T15:00:00',
    status: 'skipped',
    raw_state: 'skipped',
    try_number: 0,
    max_tries: 1,
    start_date: null,
    end_date: null,
    duration_ms: null,
    operator: 'EmailOperator',
    pool: 'default_pool',
    queue: 'default',
    executor_config: {},
    note: null,
  },
];

/**
 * Vue Flow node + edge collections for the sample DAG. Positions are
 * hand-tuned; the real DAG view (Faza 3) will compute them via dagre.
 *
 * @type {{nodes: Array<object>, edges: Array<object>}}
 */
export const SAMPLE_GRAPH = {
  nodes: [
    {
      id: 'fetch_source',
      type: 'task',
      position: { x: 0, y: 0 },
      data: {
        task_id: 'fetch_source',
        label: 'fetch_source',
        operator: 'PythonOperator',
        status: 'success',
        try_number: 1,
        max_tries: 3,
        duration_ms: 17_000,
        is_group: false,
      },
    },
    {
      id: 'profile_table',
      type: 'task',
      position: { x: 0, y: 110 },
      data: {
        task_id: 'profile_table',
        label: 'profile_table',
        operator: 'PythonOperator',
        status: 'success',
        try_number: 1,
        max_tries: 3,
        duration_ms: 45_000,
        is_group: false,
      },
    },
    {
      id: 'train_model',
      type: 'task',
      position: { x: -140, y: 220 },
      data: {
        task_id: 'train_model',
        label: 'train_model',
        operator: 'SparkSubmitOperator',
        status: 'running',
        try_number: 2,
        max_tries: 3,
        duration_ms: null,
        is_group: false,
      },
    },
    {
      id: 'validate_synthetic',
      type: 'task',
      position: { x: 140, y: 220 },
      data: {
        task_id: 'validate_synthetic',
        label: 'validate_synthetic',
        operator: 'PythonOperator',
        status: 'queued',
        try_number: 1,
        max_tries: 3,
        duration_ms: null,
        is_group: false,
      },
    },
    {
      id: 'export_to_s3',
      type: 'task',
      position: { x: 0, y: 330 },
      data: {
        task_id: 'export_to_s3',
        label: 'export_to_s3',
        operator: 'S3CreateObjectOperator',
        status: 'none',
        try_number: 0,
        max_tries: 3,
        duration_ms: null,
        is_group: false,
      },
    },
    {
      id: 'notify_failed_branch',
      type: 'task',
      position: { x: 280, y: 330 },
      data: {
        task_id: 'notify_failed_branch',
        label: 'notify_failed_branch',
        operator: 'EmailOperator',
        status: 'skipped',
        try_number: 0,
        max_tries: 1,
        duration_ms: null,
        is_group: false,
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'fetch_source', target: 'profile_table' },
    { id: 'e2', source: 'profile_table', target: 'train_model' },
    { id: 'e3', source: 'profile_table', target: 'validate_synthetic' },
    { id: 'e4', source: 'train_model', target: 'export_to_s3' },
    { id: 'e5', source: 'validate_synthetic', target: 'export_to_s3' },
    { id: 'e6', source: 'validate_synthetic', target: 'notify_failed_branch' },
  ],
};
